# Generated by Django 5.2.17 on 2026-08-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('alt_titles', models.TextField(blank=True, help_text='Pipe-separated')),
                ('author', models.CharField(max_length=300)),
                ('author_alt', models.TextField(blank=True, help_text='Pipe-separated')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['catalog_id'],
            },
        ),
    ]
