# Generated by Django 5.2.17 on 2026-08-15 21:25

import django.db.models.deletion
import scanner.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_width', models.FloatField()),
                ('bbox_height', models.FloatField()),
                ('detector_confidence', models.FloatField(blank=True, null=True)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to=scanner.models.crop_upload_path)),
                ('read_title', models.CharField(blank=True, max_length=500)),
                ('read_author', models.CharField(blank=True, max_length=300)),
                ('read_error', models.CharField(blank=True, max_length=100)),
                ('match_catalog_id', models.CharField(blank=True, max_length=16)),
                ('match_title', models.CharField(blank=True, max_length=500)),
                ('match_author', models.CharField(blank=True, max_length=300)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('match_tier', models.CharField(blank=True, choices=[('auto', 'Auto'), ('review', 'Review'), ('unmatched', 'Unmatched')], max_length=20)),
                ('match_alternates', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('pending_review', 'Pending review'), ('auto_added', 'Auto-added (high confidence)'), ('confirmed', 'Confirmed by user'), ('corrected', 'Corrected by user'), ('discarded', 'Discarded by user')], default='pending_review', max_length=20)),
                ('final_title', models.CharField(blank=True, max_length=500)),
                ('final_author', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['bbox_x'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=scanner.models.scan_image_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('local_model_ms', models.FloatField(blank=True, null=True)),
                ('vlm_total_ms', models.FloatField(blank=True, null=True)),
                ('vlm_call_count', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('catalog_id', models.CharField(blank=True, max_length=16)),
                ('series', models.CharField(blank=True, max_length=300)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('was_auto_added', models.BooleanField(default=False)),
                ('match_score_at_add', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source_detected_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_entries', to='scanner.detectedbook')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='detectedbook',
            name='scan_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_books', to='scanner.scansession'),
        ),
    ]
