"""
Generates catalog.csv.

This is checked in and re-runnable on purpose: the catalog is a fixture,
not hand-edited data, so if we want to add more deliberate messiness later
we edit ROWS below and re-run this instead of hand-patching a CSV.

Columns:
    catalog_id   stable id, referenced by the matcher's confidence-score tests
    title        canonical title as printed on the edition we picked as "primary"
    alt_titles   pipe-separated alternate titles / translations / subtitles a
                 spine or VLM read might actually produce for this book
    author       canonical author name, "First Last" form
    author_alt   pipe-separated alternate forms of the author's name a spine
                 or VLM read might actually produce (initials, accents,
                 transliterations, "Last, First")
    year         first-listed publication year for that edition
    format       hardcover / paperback / mass market / omnibus / movie tie-in
    series       series name, blank if standalone

See README.md -> "How the catalog was built" for which rows below encode
which required category of messiness (duplicate editions, US/UK titles,
homonym titles, omnibus-vs-volume, substrings, author-name variants).
"""
import csv

ROWS = [
    # --- Harry Potter: US/UK title split (#1 canonical example), initials vs full name ---
    dict(title="Harry Potter and the Philosopher's Stone",
         alt_titles="Harry Potter and the Sorcerer's Stone",
         author="J.K. Rowling", author_alt="Joanne Rowling|J. K. Rowling|Rowling, J.K.",
         year=1997, format="paperback", series="Harry Potter"),
    dict(title="Harry Potter and the Chamber of Secrets", alt_titles="",
         author="J.K. Rowling", author_alt="Joanne Rowling|Rowling, J.K.",
         year=1998, format="paperback", series="Harry Potter"),
    dict(title="Harry Potter and the Prisoner of Azkaban", alt_titles="",
         author="J.K. Rowling", author_alt="Joanne Rowling|Rowling, J.K.",
         year=1999, format="paperback", series="Harry Potter"),
    dict(title="Harry Potter and the Goblet of Fire", alt_titles="",
         author="J.K. Rowling", author_alt="Rowling, J.K.",
         year=2000, format="hardcover", series="Harry Potter"),
    dict(title="Harry Potter and the Order of the Phoenix", alt_titles="",
         author="J.K. Rowling", author_alt="Rowling, J.K.",
         year=2003, format="hardcover", series="Harry Potter"),
    dict(title="Harry Potter and the Half-Blood Prince", alt_titles="",
         author="J.K. Rowling", author_alt="Rowling, J.K.",
         year=2005, format="hardcover", series="Harry Potter"),
    dict(title="Harry Potter and the Deathly Hallows", alt_titles="",
         author="J.K. Rowling", author_alt="Rowling, J.K.",
         year=2007, format="hardcover", series="Harry Potter"),
    # second, separately-catalogued edition of book 1 -> "two editions of the same book"
    dict(title="Harry Potter and the Philosopher's Stone",
         alt_titles="Harry Potter and the Sorcerer's Stone",
         author="J.K. Rowling", author_alt="Joanne Rowling",
         year=2013, format="illustrated hardcover", series="Harry Potter"),

    # --- Pullman: US/UK title split, second example ---
    dict(title="Northern Lights", alt_titles="The Golden Compass",
         author="Philip Pullman", author_alt="Pullman, Philip",
         year=1995, format="paperback", series="His Dark Materials"),
    dict(title="The Subtle Knife", alt_titles="",
         author="Philip Pullman", author_alt="Pullman, Philip",
         year=1997, format="paperback", series="His Dark Materials"),
    dict(title="The Amber Spyglass", alt_titles="",
         author="Philip Pullman", author_alt="Pullman, Philip",
         year=2000, format="paperback", series="His Dark Materials"),

    # --- Tolkien: omnibus alongside individual volumes, two editions of same book ---
    dict(title="The Fellowship of the Ring", alt_titles="",
         author="J.R.R. Tolkien", author_alt="John Ronald Reuel Tolkien|Tolkien, J.R.R.",
         year=1954, format="paperback", series="The Lord of the Rings"),
    dict(title="The Two Towers", alt_titles="",
         author="J.R.R. Tolkien", author_alt="Tolkien, J.R.R.",
         year=1954, format="paperback", series="The Lord of the Rings"),
    dict(title="The Return of the King", alt_titles="",
         author="J.R.R. Tolkien", author_alt="Tolkien, J.R.R.",
         year=1955, format="paperback", series="The Lord of the Rings"),
    dict(title="The Lord of the Rings", alt_titles="The Lord of the Rings: The Complete Trilogy",
         author="J.R.R. Tolkien", author_alt="Tolkien, J.R.R.",
         year=1968, format="omnibus", series="The Lord of the Rings"),
    dict(title="The Hobbit", alt_titles="The Hobbit, or There and Back Again",
         author="J.R.R. Tolkien", author_alt="Tolkien, J.R.R.",
         year=1937, format="paperback", series=""),
    # second edition of The Hobbit, different printing
    dict(title="The Hobbit", alt_titles="The Hobbit, or There and Back Again",
         author="J.R.R. Tolkien", author_alt="Tolkien, J.R.R.",
         year=2012, format="movie tie-in paperback", series=""),
    dict(title="The Silmarillion", alt_titles="",
         author="J.R.R. Tolkien", author_alt="Tolkien, J.R.R.",
         year=1977, format="hardcover", series=""),

    # --- Asimov Foundation: omnibus vs volumes, substrings ---
    dict(title="Foundation", alt_titles="",
         author="Isaac Asimov", author_alt="Asimov, Isaac",
         year=1951, format="paperback", series="Foundation"),
    dict(title="Foundation and Empire", alt_titles="",
         author="Isaac Asimov", author_alt="Asimov, Isaac",
         year=1952, format="paperback", series="Foundation"),
    dict(title="Second Foundation", alt_titles="",
         author="Isaac Asimov", author_alt="Asimov, Isaac",
         year=1953, format="paperback", series="Foundation"),
    dict(title="The Foundation Trilogy", alt_titles="Foundation Trilogy: Foundation, Foundation and Empire, Second Foundation",
         author="Isaac Asimov", author_alt="Asimov, Isaac",
         year=1963, format="omnibus", series="Foundation"),

    # --- Homonym titles: two genuinely different books, same title ---
    dict(title="The Alchemist", alt_titles="",
         author="Paulo Coelho", author_alt="Coelho, Paulo",
         year=1988, format="paperback", series=""),
    dict(title="The Alchemist", alt_titles="The Secrets of the Immortal Nicholas Flamel: The Alchemyst",
         author="Michael Scott", author_alt="Scott, Michael",
         year=2007, format="paperback", series="The Secrets of the Immortal Nicholas Flamel"),
    dict(title="Nightfall", alt_titles="",
         author="Isaac Asimov", author_alt="Asimov, Isaac|Asimov & Silverberg",
         year=1990, format="paperback", series=""),
    dict(title="Nightfall", alt_titles="",
         author="Jake Halpern", author_alt="Halpern, Jake|Halpern & Kujawinski",
         year=2011, format="hardcover", series="Nightfall"),

    # --- Substrings: Dune, and Gone / Gone Girl ---
    dict(title="Dune", alt_titles="",
         author="Frank Herbert", author_alt="Herbert, Frank",
         year=1965, format="paperback", series="Dune"),
    dict(title="Dune Messiah", alt_titles="",
         author="Frank Herbert", author_alt="Herbert, Frank",
         year=1969, format="paperback", series="Dune"),
    dict(title="Children of Dune", alt_titles="",
         author="Frank Herbert", author_alt="Herbert, Frank",
         year=1976, format="paperback", series="Dune"),
    dict(title="Gone", alt_titles="",
         author="Michael Grant", author_alt="Grant, Michael",
         year=2008, format="paperback", series="Gone"),
    dict(title="Gone Girl", alt_titles="",
         author="Gillian Flynn", author_alt="Flynn, Gillian",
         year=2012, format="hardcover", series=""),

    # --- Russian authors: transliteration + Lastname,Firstname variants ---
    dict(title="Crime and Punishment", alt_titles="",
         author="Fyodor Dostoevsky", author_alt="Fyodor Dostoyevsky|Dostoevsky, Fyodor|Dostoyevsky, F.M.",
         year=1866, format="paperback", series=""),
    dict(title="The Brothers Karamazov", alt_titles="",
         author="Fyodor Dostoevsky", author_alt="Fyodor Dostoyevsky|Dostoevsky, Fyodor",
         year=1880, format="paperback", series=""),
    dict(title="War and Peace", alt_titles="",
         author="Leo Tolstoy", author_alt="Lev Tolstoy|Leo Nikolayevich Tolstoy|Tolstoy, Leo",
         year=1869, format="paperback", series=""),
    dict(title="Anna Karenina", alt_titles="",
         author="Leo Tolstoy", author_alt="Lev Tolstoy|Tolstoy, Leo",
         year=1878, format="paperback", series=""),

    # --- Accented / transliterated names ---
    dict(title="One Hundred Years of Solitude", alt_titles="Cien anos de soledad",
         author="Gabriel Garcia Marquez", author_alt="Gabriel García Márquez|Marquez, Gabriel Garcia|Márquez, Gabriel García",
         year=1967, format="paperback", series=""),
    dict(title="Love in the Time of Cholera", alt_titles="",
         author="Gabriel Garcia Marquez", author_alt="Gabriel García Márquez|Marquez, Gabriel Garcia",
         year=1985, format="paperback", series=""),

    # --- George R.R. Martin: initials spacing variants ---
    dict(title="A Game of Thrones", alt_titles="",
         author="George R.R. Martin", author_alt="George R. R. Martin|Martin, George R.R.",
         year=1996, format="paperback", series="A Song of Ice and Fire"),
    dict(title="A Clash of Kings", alt_titles="",
         author="George R.R. Martin", author_alt="George R. R. Martin|Martin, George R.R.",
         year=1998, format="paperback", series="A Song of Ice and Fire"),
    dict(title="A Storm of Swords", alt_titles="",
         author="George R.R. Martin", author_alt="George R. R. Martin",
         year=2000, format="paperback", series="A Song of Ice and Fire"),
    dict(title="A Feast for Crows", alt_titles="",
         author="George R.R. Martin", author_alt="George R. R. Martin",
         year=2005, format="hardcover", series="A Song of Ice and Fire"),
    dict(title="A Dance with Dragons", alt_titles="",
         author="George R.R. Martin", author_alt="George R. R. Martin",
         year=2011, format="hardcover", series="A Song of Ice and Fire"),

    # --- Straightforward, high-frequency "actually on people's shelves" titles ---
    dict(title="1984", alt_titles="Nineteen Eighty-Four",
         author="George Orwell", author_alt="Orwell, George|Eric Arthur Blair",
         year=1949, format="paperback", series=""),
    dict(title="Animal Farm", alt_titles="",
         author="George Orwell", author_alt="Orwell, George",
         year=1945, format="paperback", series=""),
    dict(title="To Kill a Mockingbird", alt_titles="",
         author="Harper Lee", author_alt="Lee, Harper",
         year=1960, format="paperback", series=""),
    dict(title="Pride and Prejudice", alt_titles="",
         author="Jane Austen", author_alt="Austen, Jane",
         year=1813, format="paperback", series=""),
    dict(title="The Great Gatsby", alt_titles="",
         author="F. Scott Fitzgerald", author_alt="Francis Scott Fitzgerald|Fitzgerald, F. Scott",
         year=1925, format="paperback", series=""),
    dict(title="Sapiens", alt_titles="Sapiens: A Brief History of Humankind",
         author="Yuval Noah Harari", author_alt="Harari, Yuval Noah",
         year=2011, format="paperback", series=""),
    dict(title="Atomic Habits", alt_titles="Atomic Habits: An Easy and Proven Way to Build Good Habits and Break Bad Ones",
         author="James Clear", author_alt="Clear, James",
         year=2018, format="hardcover", series=""),
    dict(title="The Da Vinci Code", alt_titles="",
         author="Dan Brown", author_alt="Brown, Dan",
         year=2003, format="paperback", series="Robert Langdon"),
    dict(title="Angels & Demons", alt_titles="",
         author="Dan Brown", author_alt="Brown, Dan",
         year=2000, format="paperback", series="Robert Langdon"),
    dict(title="The Girl with the Dragon Tattoo", alt_titles="Men Who Hate Women",
         author="Stieg Larsson", author_alt="Larsson, Stieg",
         year=2005, format="paperback", series="Millennium"),
    dict(title="Where the Crawdads Sing", alt_titles="",
         author="Delia Owens", author_alt="Owens, Delia",
         year=2018, format="hardcover", series=""),
    dict(title="Educated", alt_titles="Educated: A Memoir",
         author="Tara Westover", author_alt="Westover, Tara",
         year=2018, format="hardcover", series=""),
    dict(title="Becoming", alt_titles="",
         author="Michelle Obama", author_alt="Obama, Michelle",
         year=2018, format="hardcover", series=""),
    dict(title="The Catcher in the Rye", alt_titles="",
         author="J.D. Salinger", author_alt="Jerome David Salinger|Salinger, J.D.",
         year=1951, format="paperback", series=""),
    dict(title="Brave New World", alt_titles="",
         author="Aldous Huxley", author_alt="Huxley, Aldous",
         year=1932, format="paperback", series=""),
    dict(title="Fahrenheit 451", alt_titles="",
         author="Ray Bradbury", author_alt="Bradbury, Ray",
         year=1953, format="paperback", series=""),
    dict(title="The Kite Runner", alt_titles="",
         author="Khaled Hosseini", author_alt="Hosseini, Khaled",
         year=2003, format="paperback", series=""),
    dict(title="Life of Pi", alt_titles="",
         author="Yann Martel", author_alt="Martel, Yann",
         year=2001, format="paperback", series=""),
    dict(title="The Book Thief", alt_titles="",
         author="Markus Zusak", author_alt="Zusak, Markus",
         year=2005, format="paperback", series=""),
    dict(title="The Hunger Games", alt_titles="",
         author="Suzanne Collins", author_alt="Collins, Suzanne",
         year=2008, format="paperback", series="The Hunger Games"),
    dict(title="Catching Fire", alt_titles="",
         author="Suzanne Collins", author_alt="Collins, Suzanne",
         year=2009, format="paperback", series="The Hunger Games"),
    dict(title="Mockingjay", alt_titles="",
         author="Suzanne Collins", author_alt="Collins, Suzanne",
         year=2010, format="paperback", series="The Hunger Games"),
    dict(title="Twilight", alt_titles="",
         author="Stephenie Meyer", author_alt="Meyer, Stephenie",
         year=2005, format="paperback", series="Twilight"),
    dict(title="New Moon", alt_titles="",
         author="Stephenie Meyer", author_alt="Meyer, Stephenie",
         year=2006, format="paperback", series="Twilight"),
    dict(title="Percy Jackson and the Lightning Thief", alt_titles="The Lightning Thief",
         author="Rick Riordan", author_alt="Riordan, Rick",
         year=2005, format="paperback", series="Percy Jackson"),
    dict(title="The Road", alt_titles="",
         author="Cormac McCarthy", author_alt="McCarthy, Cormac",
         year=2006, format="paperback", series=""),
    dict(title="Slaughterhouse-Five", alt_titles="Slaughterhouse Five",
         author="Kurt Vonnegut", author_alt="Vonnegut, Kurt|Kurt Vonnegut Jr.",
         year=1969, format="paperback", series=""),
    dict(title="Catch-22", alt_titles="Catch 22",
         author="Joseph Heller", author_alt="Heller, Joseph",
         year=1961, format="paperback", series=""),
    dict(title="Thinking, Fast and Slow", alt_titles="Thinking Fast and Slow",
         author="Daniel Kahneman", author_alt="Kahneman, Daniel",
         year=2011, format="paperback", series=""),
    dict(title="Outliers", alt_titles="Outliers: The Story of Success",
         author="Malcolm Gladwell", author_alt="Gladwell, Malcolm",
         year=2008, format="hardcover", series=""),
    dict(title="The Subtle Art of Not Giving a F*ck", alt_titles="The Subtle Art of Not Giving a Fuck",
         author="Mark Manson", author_alt="Manson, Mark",
         year=2016, format="paperback", series=""),
    dict(title="Man's Search for Meaning", alt_titles="",
         author="Viktor Frankl", author_alt="Viktor E. Frankl|Frankl, Viktor",
         year=1946, format="paperback", series=""),
    dict(title="The Power of Habit", alt_titles="",
         author="Charles Duhigg", author_alt="Duhigg, Charles",
         year=2012, format="paperback", series=""),
    dict(title="Rich Dad Poor Dad", alt_titles="",
         author="Robert Kiyosaki", author_alt="Robert T. Kiyosaki|Kiyosaki, Robert",
         year=1997, format="paperback", series=""),
    dict(title="The 7 Habits of Highly Effective People", alt_titles="Seven Habits of Highly Effective People",
         author="Stephen Covey", author_alt="Stephen R. Covey|Covey, Stephen",
         year=1989, format="paperback", series=""),
    dict(title="Ender's Game", alt_titles="",
         author="Orson Scott Card", author_alt="Card, Orson Scott",
         year=1985, format="paperback", series="Ender's Saga"),
    dict(title="Neuromancer", alt_titles="",
         author="William Gibson", author_alt="Gibson, William",
         year=1984, format="paperback", series="Sprawl"),
    dict(title="Snow Crash", alt_titles="",
         author="Neal Stephenson", author_alt="Stephenson, Neal",
         year=1992, format="paperback", series=""),
    dict(title="The Martian", alt_titles="",
         author="Andy Weir", author_alt="Weir, Andy",
         year=2011, format="paperback", series=""),
    dict(title="Project Hail Mary", alt_titles="",
         author="Andy Weir", author_alt="Weir, Andy",
         year=2021, format="hardcover", series=""),
    dict(title="Circe", alt_titles="",
         author="Madeline Miller", author_alt="Miller, Madeline",
         year=2018, format="hardcover", series=""),
    dict(title="The Song of Achilles", alt_titles="",
         author="Madeline Miller", author_alt="Miller, Madeline",
         year=2011, format="paperback", series=""),
    dict(title="Normal People", alt_titles="",
         author="Sally Rooney", author_alt="Rooney, Sally",
         year=2018, format="paperback", series=""),
    dict(title="It Ends with Us", alt_titles="",
         author="Colleen Hoover", author_alt="Hoover, Colleen",
         year=2016, format="paperback", series="It Ends with Us"),
    dict(title="The Silent Patient", alt_titles="",
         author="Alex Michaelides", author_alt="Michaelides, Alex",
         year=2019, format="hardcover", series=""),
    dict(title="Gone Girl", alt_titles="", author="Gillian Flynn", author_alt="Flynn, Gillian",
         year=2012, format="movie tie-in paperback", series=""),  # 2nd edition of Gone Girl -> dup edition
    dict(title="The Girl on the Train", alt_titles="",
         author="Paula Hawkins", author_alt="Hawkins, Paula",
         year=2015, format="hardcover", series=""),
    dict(title="Big Little Lies", alt_titles="",
         author="Liane Moriarty", author_alt="Moriarty, Liane",
         year=2014, format="paperback", series=""),
    dict(title="Little Fires Everywhere", alt_titles="",
         author="Celeste Ng", author_alt="Ng, Celeste",
         year=2017, format="hardcover", series=""),
    dict(title="The Handmaid's Tale", alt_titles="",
         author="Margaret Atwood", author_alt="Atwood, Margaret",
         year=1985, format="paperback", series="The Handmaid's Tale"),
    dict(title="The Testaments", alt_titles="",
         author="Margaret Atwood", author_alt="Atwood, Margaret",
         year=2019, format="hardcover", series="The Handmaid's Tale"),
    dict(title="Never Let Me Go", alt_titles="",
         author="Kazuo Ishiguro", author_alt="Ishiguro, Kazuo",
         year=2005, format="paperback", series=""),
    dict(title="The Remains of the Day", alt_titles="",
         author="Kazuo Ishiguro", author_alt="Ishiguro, Kazuo",
         year=1989, format="paperback", series=""),
    dict(title="Beloved", alt_titles="",
         author="Toni Morrison", author_alt="Morrison, Toni",
         year=1987, format="paperback", series=""),
    dict(title="The Color Purple", alt_titles="",
         author="Alice Walker", author_alt="Walker, Alice",
         year=1982, format="paperback", series=""),
    dict(title="Of Mice and Men", alt_titles="",
         author="John Steinbeck", author_alt="Steinbeck, John",
         year=1937, format="paperback", series=""),
    dict(title="East of Eden", alt_titles="",
         author="John Steinbeck", author_alt="Steinbeck, John",
         year=1952, format="paperback", series=""),
    dict(title="The Grapes of Wrath", alt_titles="",
         author="John Steinbeck", author_alt="Steinbeck, John",
         year=1939, format="paperback", series=""),
    dict(title="The Bell Jar", alt_titles="",
         author="Sylvia Plath", author_alt="Plath, Sylvia",
         year=1963, format="paperback", series=""),
    dict(title="One Flew Over the Cuckoo's Nest", alt_titles="",
         author="Ken Kesey", author_alt="Kesey, Ken",
         year=1962, format="paperback", series=""),
    dict(title="The Lion, the Witch and the Wardrobe", alt_titles="",
         author="C.S. Lewis", author_alt="Clive Staples Lewis|Lewis, C.S.",
         year=1950, format="paperback", series="The Chronicles of Narnia"),
    dict(title="Prince Caspian", alt_titles="",
         author="C.S. Lewis", author_alt="Lewis, C.S.",
         year=1951, format="paperback", series="The Chronicles of Narnia"),
    dict(title="The Chronicles of Narnia", alt_titles="The Chronicles of Narnia: The Complete Series",
         author="C.S. Lewis", author_alt="Lewis, C.S.",
         year=2001, format="omnibus", series="The Chronicles of Narnia"),
    dict(title="Good Omens", alt_titles="Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch",
         author="Terry Pratchett and Neil Gaiman", author_alt="Gaiman, Neil and Pratchett, Terry|Neil Gaiman & Terry Pratchett",
         year=1990, format="paperback", series=""),
    dict(title="American Gods", alt_titles="",
         author="Neil Gaiman", author_alt="Gaiman, Neil",
         year=2001, format="paperback", series=""),
    dict(title="Coraline", alt_titles="",
         author="Neil Gaiman", author_alt="Gaiman, Neil",
         year=2002, format="paperback", series=""),
    dict(title="The Ocean at the End of the Lane", alt_titles="",
         author="Neil Gaiman", author_alt="Gaiman, Neil",
         year=2013, format="hardcover", series=""),
    dict(title="Stardust", alt_titles="",
         author="Neil Gaiman", author_alt="Gaiman, Neil",
         year=1997, format="paperback", series=""),
    dict(title="A Song of Ice and Fire", alt_titles="A Game of Thrones: The Story Continues",
         author="George R.R. Martin", author_alt="George R. R. Martin",
         year=2016, format="omnibus", series="A Song of Ice and Fire"),  # omnibus vs individual volumes above
    dict(title="The Silmarillion", alt_titles="",
         author="J.R.R. Tolkien", author_alt="Tolkien, J.R.R.",
         year=1999, format="illustrated hardcover", series=""),  # 2nd edition, dup
    dict(title="Emma", alt_titles="",
         author="Jane Austen", author_alt="Austen, Jane",
         year=1815, format="paperback", series=""),
    dict(title="Sense and Sensibility", alt_titles="",
         author="Jane Austen", author_alt="Austen, Jane",
         year=1811, format="paperback", series=""),
    dict(title="Jane Eyre", alt_titles="",
         author="Charlotte Bronte", author_alt="Charlotte Brontë|Bronte, Charlotte",
         year=1847, format="paperback", series=""),
    dict(title="Wuthering Heights", alt_titles="",
         author="Emily Bronte", author_alt="Emily Brontë|Bronte, Emily",
         year=1847, format="paperback", series=""),
    dict(title="Frankenstein", alt_titles="Frankenstein; or, The Modern Prometheus",
         author="Mary Shelley", author_alt="Shelley, Mary",
         year=1818, format="paperback", series=""),
    dict(title="Dracula", alt_titles="",
         author="Bram Stoker", author_alt="Stoker, Bram",
         year=1897, format="paperback", series=""),
    dict(title="The Picture of Dorian Gray", alt_titles="",
         author="Oscar Wilde", author_alt="Wilde, Oscar",
         year=1890, format="paperback", series=""),
    dict(title="Moby-Dick", alt_titles="Moby Dick; or, The Whale",
         author="Herman Melville", author_alt="Melville, Herman",
         year=1851, format="paperback", series=""),
    dict(title="The Odyssey", alt_titles="",
         author="Homer", author_alt="",
         year=-700, format="paperback", series=""),
    dict(title="Meditations", alt_titles="",
         author="Marcus Aurelius", author_alt="Aurelius, Marcus",
         year=180, format="paperback", series=""),
    dict(title="The Stranger", alt_titles="L'Etranger|The Outsider",
         author="Albert Camus", author_alt="Camus, Albert",
         year=1942, format="paperback", series=""),
    dict(title="Siddhartha", alt_titles="",
         author="Hermann Hesse", author_alt="Hesse, Hermann",
         year=1922, format="paperback", series=""),
    dict(title="The Little Prince", alt_titles="Le Petit Prince",
         author="Antoine de Saint-Exupery", author_alt="Antoine de Saint-Exupéry|Saint-Exupery, Antoine de",
         year=1943, format="hardcover", series=""),
    dict(title="All the Light We Cannot See", alt_titles="",
         author="Anthony Doerr", author_alt="Doerr, Anthony",
         year=2014, format="hardcover", series=""),
    dict(title="The Night Circus", alt_titles="",
         author="Erin Morgenstern", author_alt="Morgenstern, Erin",
         year=2011, format="paperback", series=""),
    dict(title="The Nightingale", alt_titles="",
         author="Kristin Hannah", author_alt="Hannah, Kristin",
         year=2015, format="hardcover", series=""),
    dict(title="A Man Called Ove", alt_titles="En man som heter Ove",
         author="Fredrik Backman", author_alt="Backman, Fredrik",
         year=2012, format="paperback", series=""),
    dict(title="The Vanishing Half", alt_titles="",
         author="Brit Bennett", author_alt="Bennett, Brit",
         year=2020, format="hardcover", series=""),
    dict(title="Klara and the Sun", alt_titles="",
         author="Kazuo Ishiguro", author_alt="Ishiguro, Kazuo",
         year=2021, format="hardcover", series=""),
    dict(title="The Midnight Library", alt_titles="",
         author="Matt Haig", author_alt="Haig, Matt",
         year=2020, format="hardcover", series=""),
    dict(title="Verity", alt_titles="",
         author="Colleen Hoover", author_alt="Hoover, Colleen",
         year=2018, format="paperback", series=""),
    dict(title="Atomic Habits", alt_titles="Atomic Habits: An Easy and Proven Way to Build Good Habits and Break Bad Ones",
         author="James Clear", author_alt="Clear, James",
         year=2018, format="paperback", series=""),  # 2nd edition dup
]

def build():
    for i, row in enumerate(ROWS, start=1):
        row["catalog_id"] = f"CAT{i:04d}"
    fields = ["catalog_id", "title", "alt_titles", "author", "author_alt", "year", "format", "series"]
    with open("catalog.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for row in ROWS:
            w.writerow({k: row.get(k, "") for k in fields})
    print(f"Wrote {len(ROWS)} rows to catalog.csv")

if __name__ == "__main__":
    build()
